### ISSUE TITLE
BUG: NG8002: Can't bind to 'trigger' since it isn't a known property of 'div'.

### ISSUE THREAD

**Issue by marfrede** [tonysamperi/ngx-float-ui#10]
**Describe the bug**
I get a compiler error whenever I want to use the "trigger" attribute with squared-braces like:
```html
<float-ui-content #myPopperContent> I'm popper :) </float-ui-content>
<div
  [floatUi]="myPopperContent"
  [hideOnClickOutside]="true"
  [trigger]="'hover'"
  style="width: 100px; height: 100px; margin: 100px"
>
  hello
</div>
```

**To Reproduce**
[stackblitz reproducing the bug](https://stackblitz.com/edit/stackblitz-starters-rjn1un?file=src%2Fmain.html)

**Expected behavior**
I expect this application to compile without errors, so that the trigger can be set.

**Screenshots**
![image](https://github.com/tonysamperi/ngx-float-ui/assets/46896843/df0dda7b-c93d-4dba-9460-51eb879f96ba)

**Versions**
 - ngx-float-ui version `17.0.1`
 - @angular/core version `17.1.1`
 - ~@angular/material version~
 - typescript version `~4.0.2`

**Context**
- Whenever I use the trigger attribute without squared-braces there is NO compiler error, but then it (e.g. `trigger="hover"`) takes no effect. It sticks to the default trigger `click`.
- Same compiler error happens on attribute `target`

**Comment by tonysamperi** [comment]
Hi, it's a documentation issue, the input is actually called `showTrigger`.

Cheers
