### ISSUE TITLE
It appears Delay and Timeout are not supported

### ISSUE THREAD

**Issue by BowlinAndBoatin** [tonysamperi/ngx-float-ui#14]
**Describe the bug**
The float UI content component doesn't appear to support delay or timeout attributes. 

**To Reproduce**
e.g. ```<span class="ellipses-overflow" [floatUi]="popperSummary" [delay]="1000">{{ someObject.name }}</span>```

delay is underlined, and unknown in multiple IDEs. 

Error:
``` error NG8002: Can't bind to 'delay' since it isn't a known property of 'span'.```
``` error NG8002: Can't bind to 'timeout' since it isn't a known property of 'span'.```

**Expected behavior**
Attributes delay and timeout are supported.

** Versions
    "@angular/animations": "^16.2.12",
    "@angular/common": "^16.2.12",
    "@angular/compiler": "^16.2.12",
    "@angular/core": "^16.2.12",
    "@angular/forms": "^16.2.12",
    "@angular/platform-browser": "^16.2.12",
    "@angular/platform-browser-dynamic": "^16.2.12",
    "@angular/router": "^16.2.12",
    "@floating-ui/dom": "^1.6.3",
      "ngx-float-ui": "^17.1.0",
    typescript: 4.9.5

**Comment by tonysamperi** [comment]
They are! I just renamed them to `showDelay` and `hideTimeout` to make it easier to understand what they do!
I'll fix this in the next release!
