### ISSUE TITLE
BUG: ViewChild with floatUiViewRef Throws Undefined Property StartsWith

### ISSUE THREAD

**Issue by BowlinAndBoatin** [tonysamperi/ngx-float-ui#15]
**Describe the bug**
Prior to switching from npx-popper and popperjs you were able to use `@ViewChild` and reference the popper content `popperViewRef` which would allow you to update the popper content when changes occurred dynamically.   After migrating to ngx-float-ui and floating-ui that previously working functionality now throws exceptions.
I added the `placement` input where the component is referenced in the html like bug https://github.com/tonysamperi/ngx-float-ui/issues/12 suggests, but that doesn't change the behavior.   

Is there another way we're suppose to be updating the floatUiViewRef dynamically w/o needing to create subscriptions?

Example component:
```
export class MyComponent implements OnInit, OnDestroy, OnChanges {

  /**
   * Reference to the content .
   */
  @ViewChild('popperContent', { static: true })
  floatUiViewRef: NgxFloatUiContentComponent;

ngOnChanges(changes: SimpleChanges): void {
        this.setErrorState('Not connected to the server.');
       ...... (other functions which use `changes`
    }

private setErrorState(message: SafeHtml) {
     if (this.message!== message) {
      this.message= message;
      // Update the messag
      this.floatUiViewRef.update();
    }
  }
}
```

html:
```
<div class="progress-container" data-test="progress-bar" [floatUi]="popperContent" [placement]="NgxFloatUiPlacements.AUTO" [showDelay]="250" [hideTimeout]="250">

<float-ui-content #popperContent>
  <div [innerHtml]="progressMessage"></div>
  <div *ngIf="helpMessage" class="pt-1">
    <a *ngIf="helpRoute" routerLink="{{helpRoute}}">{{helpMessage}}</a>
    <span *ngIf="!helpRoute">{{helpMessage}}</span>
  </div>
</float-ui-content>
```

**Expected behavior**
The floatUiViewRef to update without raising an exception.

**Screenshots**
```
ERROR TypeError: Cannot read properties of undefined (reading 'startsWith')
    at NgxFloatUiContentComponent._computePosition (ngx-float-ui.mjs:174:63)
    at NgxFloatUiContentComponent.update (ngx-float-ui.mjs:160:14)
    at MyComponent.update (my-component.component.ts:272:28)
    at MyComponent.setErrorState (my-componentcomponent.ts:316:10)
    at MyComponent.setState (my-componentcomponent.ts:347:14)
    at MyComponent..ngOnChanges (my-component.component.ts:209:14)
    at ServicePlugComponent.rememberChangeHistoryAndInvokeOnChangesHook (core.mjs:3032:14)
    at callHookInternal (core.mjs:4024:14)
    at callHook (core.mjs:4055:9)
    at callHooks (core.mjs:4006:17)
```

**Desktop (if execution):**
 - OS: Windows
 - Browser: Chrome 121.0.6167.161

** Versions
"@angular/animations": "^16.2.12",
"@angular/common": "^16.2.12",
"@angular/compiler": "^16.2.12",
"@angular/core": "^16.2.12",
"@angular/forms": "^16.2.12",
"@angular/platform-browser": "^16.2.12",
"@angular/platform-browser-dynamic": "^16.2.12",
"@angular/router": "^16.2.12",
"@floating-ui/dom": "^1.6.3",
"ngx-float-ui": "^17.1.1",
typescript: 4.9.5

**Comment by tonysamperi** [comment]
Hi @BowlinAndBoatin I know it's a lot to ask, but can you create a blitz?

**Comment by tonysamperi** [comment]
@BowlinAndBoatin also why are you using v17 with Angular 16?

**Comment by BowlinAndBoatin** [comment]
> also why are you using v17 with Angular 16?
Thats a great question.  Simple answer, didn't think about it, installed it, compiled, and ran mostly without error (only the reported error).  I can try downgrading to 16.x release of npx-float-ui

**Comment by BowlinAndBoatin** [comment]
> Hi @BowlinAndBoatin I know it's a lot to ask, but can you create a blitz?

I can try. Its likely not going to happen quickly.

**Comment by BowlinAndBoatin** [comment]
> > also why are you using v17 with Angular 16?
> 
> Thats a great question. Simple answer, didn't think about it, installed it, compiled, and ran mostly without error (only the reported error). I can try downgrading to 16.x release of npx-float-ui

Same error, same line number after downgrade.

**Comment by tonysamperi** [comment]
> > > also why are you using v17 with Angular 16?
> > 
> > 
> > Thats a great question. Simple answer, didn't think about it, installed it, compiled, and ran mostly without error (only the reported error). I can try downgrading to 16.x release of npx-float-ui
> 
> Same error, same line number after downgrade.

ahaha I was aware that downgrading wouldn't solve, I was just curious 😂
By the way the latest v16 is identical to the latest v17 so you can keep it this way.
I'm preparing a starter blitz for you to edit with your logics...

**Comment by tonysamperi** [comment]
@BowlinAndBoatin here you go...

It should require minimal effort for you!

[https://stackblitz.com/edit/ts-angular-16-float-ui](https://stackblitz.com/edit/ts-angular-16-float-ui)

**Comment by BowlinAndBoatin** [comment]
I'm a little bit further... 
If i wrap the call `this.floatUiViewRef.update()` in the `ngOnChanges` function with 
```
     setTimeout(() => {
        this.floatUiViewRef.update();
      }, 1000);
}
```
The error is gone.  Is there a timing bug with using `showDelay` and `hideTimeout`.  The component appears to be getting the updates as well.

**Comment by tonysamperi** [comment]
> I'm a little bit further... If i wrap the call `this.floatUiViewRef.update()` in the `ngOnChanges` function with
> 
> ```
>      setTimeout(() => {
>         this.floatUiViewRef.update();
>       }, 1000);
> }
> ```
> 
> The error is gone. Is there a timing bug with using `showDelay` and `hideTimeout`. The component appears to be getting the updates as well.

Yes, I figured that something related to the init of the directive may be the issue...
If you can reproduce in the blitz then I can see the precise reason and maybe address the issue...
Maybe some observable, like you were saying, or something like that...

Cheers

**Comment by tonysamperi** [comment]
Ah now I see...
I think you could use the ngAfterViewInit to know that the component view is ready and then you can start triggering the updates...

**Comment by BowlinAndBoatin** [comment]
Issue was related to timing with the observables. I have a work around.
