### ISSUE TITLE
BUG: Styling issues - red arrow

### ISSUE THREAD

**Issue by TobiasJu** [tonysamperi/ngx-float-ui#16]
**Describe the bug**
I use your library in my Angular 16 component. But it's hard to set the styling. The default is transparent with a **red** arrow, why?
Can you set the default to white background with white arrow please?

All i want is white background and that the popup is on the higest z-index. 
To achive this i had to use the deprecated ::ng-deep instructon.

1. Install the package
2. Import the module
3. creat a <float-ui-content #testFlyout>TEST</float-ui-content>
4. linked it to a button <button [floatUi]="testFlyout">Test</button>
5. click the button
6. The popup is transparent and some UI elements are in front of the popup, also the arrow is red.

**Current deprecated fix:**
```
// Overwrite float-ui default colors
:host ::ng-deep .float-ui-container {
  background-color: white;
  z-index: 1;
}
```

**Expected behavior**
Please make the default background white for the .float-ui-container and .float-ui-arrow

**Screenshots**
![image](https://github.com/tonysamperi/ngx-float-ui/assets/32335067/879a2ad6-d8cb-4d2c-b02d-68bfd41f8754)

**Desktop:**
 - OS: Ubuntu
 - Browser chrome

** Versions**
 - "ngx-float-ui": "^16.0.2",
 - "@angular/core": "16.2.11",
 - "@angular/material": "16.2.11",
 - "typescript": "5.1.6"

**Additional context**
Actually i did not find a way to make the arrow appear white. currently it's red.

**Comment by TobiasJu** [comment]
Well i did fix it, but it's waaay to shady.

```
  ngAfterViewInit() {
    Array.from(document.getElementsByClassName('float-ui-arrow')).forEach((arrow: HTMLElement) => {
      arrow.style.backgroundColor = 'white';
    });
  }
```

**Comment by tonysamperi** [comment]
@TobiasJu ahah you're right mate! I guess that's something i put there while developing and forgot to remove it...
I wonder how no one noticed before...

Fixing in v16.0.3 and v17.1.3

**Comment by tonysamperi** [comment]
Done

**Comment by TobiasJu** [comment]
Thanks for the quick response! 
But at the same time the arrow is now hidden and your directive "arrowClass" does not add a class to the arrow.

**Comment by tonysamperi** [comment]
Please create a blitz.
I think you're doing unnecessary stuff instead of simply using the themes.
The background has nothing to with the arrow, because it's made of border. 

Thanks
