### ISSUE TITLE
BUG: Can't bind to 'floatUi' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by thanh-ngc171** [tonysamperi/ngx-float-ui#17]
**Describe the bug**
After following the instructions on the main GitHub page, I can't use [floatUI] directive on the div tag and other options. Given error was thrown: "Can't bind to 'floatUi' since it isn't a known property of 'div'"

**To Reproduce**
I have tried other angular sandbox places to make sure it was not because of my project, and the issue persists. Please visit the following stackblitz: https://stackblitz.com/edit/angular-ivy-gpssw4?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fapp.component.html

**Expected behavior**
Able to use [floatUI] directive 

**Screenshots**
![image](https://github.com/tonysamperi/ngx-float-ui/assets/128768707/1967a431-f5c9-4b06-96a4-05ba7ec7160b)

![image](https://github.com/tonysamperi/ngx-float-ui/assets/128768707/96506b3c-a713-47c2-bebf-48fab621fc6b)

![image](https://github.com/tonysamperi/ngx-float-ui/assets/128768707/b89a1023-9cb3-4008-9b19-8039427a3eb2)

**Desktop (if execution):**
 - OS: Window
 - Browser: Chrome

** Versions
 - ngx-float-ui version 17.1.3
 - @angular/core version 14.0.4(my project) 15.2.10(sandbox)
 - @angular/material version My project don't use Material
 - typescript version ~4.7.2

**Comment by tonysamperi** [comment]
And why that should be supposed to work?
Why did you open this?
