### ISSUE TITLE
Angular 15 version support

### ISSUE THREAD

**Issue by szuperaz** [tonysamperi/ngx-float-ui#18]
This is not a bug report, I'm currently using `ngx-popperjs` in an Angular library that supports multiple Angular versions. I'd like to move on to the `ngx-float-ui`, the only blocker is Angular version support. I'm writing to ask if you'd consider adding support for Angular 15?

**Comment by tonysamperi** [comment]
Hey @szuperaz 

this is exactly what you was supposed to do.
Unfortunately it's a matter of numbers. If I got a certain number of requests, I would definitely do my best to release v15 as well.

With the scientist that thinks to run v17 in Angular 15 we would have 2 requests...

Let's keep this open a bit...if we can get a few upvotes I'll do the job!

**Comment by szuperaz** [comment]
I understand, I'm also happy to do the initial contribution, but still, all new features/bugfixes require work from you, so it only makes sense to commit if you also see the value in it.

**Comment by szuperaz** [comment]
This is the library where I'd like to use the library: https://www.npmjs.com/package/stream-chat-angular - full disclosure some of my teammates upvoted the issue as well 🙂

**Comment by szuperaz** [comment]
Thank you

**Comment by tonysamperi** [comment]
Hey @szuperaz released!
