### ISSUE TITLE
Can't bind to 'target' since it isn't a known property

### ISSUE THREAD

**Issue by ChrisLindeman** [tonysamperi/ngx-float-ui#19]
**Describe the bug**
Attempting to set a specific target element gives the following:
`error NG8002: Can't bind to 'target' since it isn't a known property of 'div'.`
Perhaps it is a documentation error?

**To Reproduce**
Use [target] prop on a [floatUi] element

**Expected behavior**
Specify a different reference element other the the one hosting the directive

** Versions**
 - "ngx-float-ui": "^17.1.3"
 - "@angular/core": "^17.3.7"
 - "@angular/material": "^17.3.6"
 - "typescript": "~5.4.5"

**Comment by tonysamperi** [comment]
Hi @ChrisLindeman please create a Blitz reproducing the problem.

Thanks

**Comment by ChrisLindeman** [comment]
Sure:
https://stackblitz.com/edit/ts-angular-16-float-ui-4ncddl?file=src%2Fapp%2Fapp.component.html

**Comment by tonysamperi** [comment]
Closed with 17.1.4
