### ISSUE TITLE
BUG: Unable to pass middleware

### ISSUE THREAD

**Issue by piacentero** [tonysamperi/ngx-float-ui#20]
**Describe the bug**
it is not possible to pass middlewares (ex: offset or size) as input to the directive.

**Expected behavior**
Have the possibility to pass middlewares as it was previously implemented with modifiers for popperjs wrapper.

**Screenshots**
![image](https://github.com/tonysamperi/ngx-float-ui/assets/16261622/68a5d2c4-f7e7-40e2-af8a-2e1880552f4e)

**Versions**
 - ngx-float-ui [17.1.3]
 - @angular/core [17.0.0]
 - typescript [5.4.5]

**Comment by tonysamperi** [comment]
These libraries are different, in Popper.js I had to introduce modifiers to handle the "no-flip".
Here modifiers are basically overkill and mostly risk to mess up with the compute inside.
