### ISSUE TITLE
Type 'string' is not assignable to type 'NgxFloatUiPlacements'.

### ISSUE THREAD

**Issue by lauraalvarezzz1** [tonysamperi/ngx-float-ui#21]
**NOTE**

**Describe the bug**
In documentation, we have demo to input placement and trigger as a strings base on enums NgxFloatUiPlacements and NgxFloatUiTriggers, but when we put por example: [placement]="'right'"
Issue comes up: Type '"right"' is not assignable to type 'NgxFloatUiPlacements'

**Screenshots**
![image](https://github.com/tonysamperi/ngx-float-ui/assets/21085858/ef26ae0f-1706-4830-9ee4-494cabd2a233)

**Desktop (if execution):**

** Versions
 "@angular/common": "^17.3.0",
    "@angular/core": "^17.3.0",
    "ngx-float-ui": "17.1.3"

**Comment by tonysamperi** [comment]
Read the readme
