### ISSUE TITLE
Version 18 has incorrect Angular peer dependency

### ISSUE THREAD

**Issue by szuperaz** [tonysamperi/ngx-float-ui#26]
**Describe the bug**
Version 18 incorrectly specifies Angular version (17 instead of 18): https://github.com/tonysamperi/ngx-float-ui/blob/master/projects/ngx-float-ui/package.json#L32-L33

**To Reproduce**

1. Open an Angular 18 project
2. Run `npm install ngx-float-ui@18`
4. See error:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: chat-example@0.0.0
npm ERR! Found: @angular/common@18.0.4
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^18.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^17.0.0" from ngx-float-ui@18.0.0
npm ERR! node_modules/ngx-float-ui
npm ERR!   ngx-float-ui@"18" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
```

**Expected behavior**
No errors during install

** Versions
 - ngx-float-ui version: 18
 - @angular/core version: 18

**Comment by tonysamperi** [comment]
Fixed in v18.0.1 thanks!

**Comment by tonysamperi** [comment]
@szuperaz sorry. Now it's really gone. In one week if nothing comes out I will promote it to release with v18.0.1

**Comment by szuperaz** [comment]
Thank you
