### ISSUE TITLE
BUG: 'auto' is no longer supported

### ISSUE THREAD

**Issue by ruimendes29** [tonysamperi/ngx-float-ui#9]
Currently, the 'auto' position for the popover is not working, I assume this is an issue because floating-ui no longer supports 'auto' as placement but rather uses middleware methods to keep the popover in view. Would it be possible to implement a way to support 'auto' like popper-js did?

**Comment by tonysamperi** [comment]
Yes, there's an issue on ngx-popperjs.
I'm implementing this asap...I need a few days...

**Comment by tonysamperi** [comment]
Done in v17.1.0! 🎉
